Formatted Code + Code Improvement

diff --git a/python/rop-ps4-8cc b/python/rop-ps4-8cc
--- a/python/rop-ps4-8cc
+++ b/python/rop-ps4-8cc
@@ -7,7 +7,7 @@ if [ "x${self:0:1}" != x/ ]; then
 fi
 
 self="$(dirname "$self")"
-temp="./temp"
+temp="./temp_ropps48cc"
 rm -rf "$temp"
 mkdir -p "$temp"
 
@@ -15,7 +15,7 @@ failure () {
     local error_message="$1"
 
     # Print the error message
-    echo "Error: $error_message"
+    echo "rop-ps4-8cc Error: $error_message"
 
     # Exit with error code 1
     exit 1
@@ -29,19 +29,22 @@ cat "$temp/pp.s" > "$temp/linked.s" || failure
 touch "$temp/custom.rop"
 
 while [ "x$1" != x ]; do
-    ii="$1"
-    ll="${#ii}"
-    ll="$((ll-4))"
+    input_file="$1"
+    file_len="${#input_file}"
+    file_len="$((file_len-4))"
     
-    if [ "${ii:ll}" == ".rop" ]; then
-        cat "$ii" >> "$temp/custom.rop"
+    if [ "${input_file:file_len}" == ".rop" ]; then
+        cat "$input_file" >> "$temp/custom.rop"
     else
         cat > "$temp/pp.c" << EOF
 unsigned short __builtin_bswap16(unsigned short);
 unsigned int __builtin_bswap32(unsigned int);
 unsigned long long __builtin_bswap64(unsigned long long);
 EOF
-        cpp -P -D__PS4__ -DPRINTF_DISABLE_SUPPORT_FLOAT '-D__asm__(...)=' '-D__restrict=' '-D__extension__=' '-D__builtin_va_list=int' '-D__inline=' '-D__attribute__(x)=' '-D__asm(...)=' '-D__builtin_offsetof(a, b)=(((char*)&((a*)0)->b)-(char*)0)' -isystem "$self/../include" -isystem "$self/../.." -isystem "$self/../../freebsd-headers" -nostdinc "$1" >> "$temp/pp.c" || failure
+        cpp -P -D__PS4__ -DPRINTF_DISABLE_SUPPORT_FLOAT '-D__asm__(...)=' '-D__restrict=' '-D__extension__=' '-D__builtin_va_list=int' '-D__inline=' \
+            '-D__attribute__(x)=' '-D__asm(...)=' '-D__builtin_offsetof(a, b)=(((char*)&((a*)0)->b)-(char*)0)' -isystem "$self/../include" \
+            -isystem "$self/../.." -isystem "$self/../../freebsd-headers" -nostdinc "$1" >> "$temp/pp.c" || failure
+        
         "$self/../8cc" "$temp/pp.c" -S -o "$temp/pp.s" || failure
         cat "$temp/pp.s" >> "$temp/linked.s" || failure
         echo >> "$temp/linked.s" || failure
